# Generated by Django 3.1.13 on 2021-10-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0122_auto_20211001_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='windmodel',
            name='existing_kw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
