# Generated by Django 3.1.13 on 2021-10-26 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0124_windmodel_existing_wind_om_cost_us_dollars'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('min_kg', models.FloatField(blank=True, null=True)),
                ('max_kg', models.FloatField(blank=True, null=True)),
                ('installed_cost_us_dollars_per_gal', models.FloatField(blank=True, null=True)),
                ('om_cost_us_dollars_per_gal', models.FloatField(blank=True, null=True)),
                ('macrs_option_years', models.IntegerField(blank=True, null=True)),
                ('macrs_bonus_pct', models.FloatField(blank=True, null=True)),
                ('can_supply_fc', models.BooleanField(blank=True, null=True)),
                ('size_kg', models.FloatField(blank=True, null=True)),
                ('year_one_hydrogen_soc_series', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
                ('year_one_hydrogen_to_fuel_cell_series_kg_per_hr', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
