# Generated by Django 3.1.13 on 2021-11-12 00:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0125_tankmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCellModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('min_kw', models.FloatField(blank=True, null=True)),
                ('max_kw', models.FloatField(blank=True, null=True)),
                ('installed_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('om_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('om_cost_us_dollars_per_kwh', models.FloatField(blank=True, null=True)),
                ('hydrogen_slope_kg_per_kwh', models.FloatField(blank=True, null=True)),
                ('hydrogen_intercept_kg_per_hr', models.FloatField(blank=True, null=True)),
                ('min_turn_down_pct', models.FloatField(blank=True, null=True)),
                ('macrs_option_years', models.IntegerField(blank=True, null=True)),
                ('macrs_bonus_pct', models.FloatField(blank=True, null=True)),
                ('macrs_itc_reduction', models.FloatField(blank=True, null=True)),
                ('federal_itc_pct', models.FloatField(blank=True, null=True)),
                ('state_ibi_pct', models.FloatField(blank=True, null=True)),
                ('state_ibi_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('utility_ibi_pct', models.FloatField(blank=True, null=True)),
                ('utility_ibi_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('federal_rebate_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('state_rebate_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('state_rebate_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('utility_rebate_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('utility_rebate_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('pbi_us_dollars_per_kwh', models.FloatField(blank=True, null=True)),
                ('pbi_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('pbi_years', models.FloatField(blank=True, null=True)),
                ('pbi_system_max_kw', models.FloatField(blank=True, null=True)),
                ('can_net_meter', models.BooleanField(blank=True, null=True)),
                ('can_wholesale', models.BooleanField(blank=True, null=True)),
                ('can_export_beyond_site_load', models.BooleanField(blank=True, null=True)),
                ('can_curtail', models.BooleanField(blank=True, null=True)),
                ('useful_life_years', models.FloatField(blank=True, null=True)),
                ('size_kw', models.FloatField(blank=True, null=True)),
                ('average_yearly_energy_produced_kwh', models.FloatField(blank=True, null=True)),
                ('year_one_variable_om_cost_us_dollars', models.FloatField(blank=True, null=True)),
                ('hydrogen_used_series_kg', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None)),
            ],
        ),
        migrations.RenameField(
            model_name='tankmodel',
            old_name='year_one_hydrogen_soc_series',
            new_name='year_one_tank_soc_series',
        ),
        migrations.RemoveField(
            model_name='tankmodel',
            name='year_one_hydrogen_to_fuel_cell_series_kg_per_hr',
        ),
    ]
