# Generated by Django 3.1.13 on 2021-11-13 19:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0126_auto_20211112_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tankmodel',
            old_name='installed_cost_us_dollars_per_gal',
            new_name='installed_cost_us_dollars_per_kg',
        ),
        migrations.RenameField(
            model_name='tankmodel',
            old_name='om_cost_us_dollars_per_gal',
            new_name='om_cost_us_dollars_per_kg',
        ),
        migrations.RemoveField(
            model_name='tankmodel',
            name='can_supply_fc',
        ),
        migrations.AddField(
            model_name='fuelcellmodel',
            name='year_one_power_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
