# Generated by Django 3.1.13 on 2021-12-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0127_auto_20211113_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelcellmodel',
            old_name='year_one_power_production_series_kw',
            new_name='year_one_power_production_series',
        ),
    ]
