# Generated by Django 3.1.13 on 2021-12-30 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0128_auto_20211215_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcellmodel',
            name='to_massproducer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
