# Generated by Django 3.1.13 on 2021-12-31 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0129_fuelcellmodel_to_massproducer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelcellmodel',
            old_name='to_massproducer',
            new_name='to_battery',
        ),
        migrations.AddField(
            model_name='tankmodel',
            name='year_one_tank_soc_ptc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
