# Generated by Django 3.1.13 on 2022-01-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0131_auto_20211231_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='massproducermodel',
            name='lcoh_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
