# Generated by Django 3.1.13 on 2022-01-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0132_massproducermodel_lcoh_us_dollars_per_kwh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massproducermodel',
            old_name='lcoh_us_dollars_per_kwh',
            new_name='lcoh_us_dollars_per_kg',
        ),
    ]
