# Generated by Django 3.1.13 on 2022-01-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0134_tankmodel_hydrogen_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='maximum_grid_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
