# Generated by Django 3.1.13 on 2022-06-16 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0135_electrictariffmodel_maximum_grid_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='windmodel',
            name='capacity_factor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
