# Generated by Django 3.1.13 on 2022-07-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0137_scenariomodel_rated_electrolyzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='windmodel',
            name='ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
