# Generated by Django 3.1.13 on 2022-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0138_windmodel_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='ratio_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
