# Generated by Django 3.1.13 on 2022-11-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0139_scenariomodel_ratio_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('csp', models.BooleanField(blank=True, null=True)),
                ('size_kw', models.FloatField(blank=True, null=True)),
                ('average_yearly_energy_produced_kwh', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
