# Generated by Django 3.1.13 on 2022-11-23 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0140_cspmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cspmodel',
            name='can_curtail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='can_net_meter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='can_wholesale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='federal_itc_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='federal_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='installed_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='macrs_itc_reduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='min_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='om_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='pbi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='pbi_system_max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='pbi_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='pbi_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='state_ibi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='state_ibi_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='state_rebate_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='state_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='utility_ibi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='utility_ibi_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='utility_rebate_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='utility_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='year_one_electric_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='year_one_to_battery_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='year_one_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
