# Generated by Django 3.1.13 on 2022-11-24 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0141_auto_20221123_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cspmodel',
            old_name='csp',
            new_name='cspflage',
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='year_one_curtailed_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cspmodel',
            name='year_one_to_massproducer_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
