# Generated by Django 3.1.13 on 2022-11-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0142_auto_20221124_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cspmodel',
            old_name='cspflage',
            new_name='cspflag',
        ),
    ]
